// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.siros_dc_matcher_ffi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import android.os.Build
import androidx.annotation.RequiresApi
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_siros_dc_matcher_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_siros_dc_matcher_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "siros_dc_matcher_ffi"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}












































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "siros_dc_matcher_ffi")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
        // The Cleaner for the whole library
        internal val CLEANER: UniffiCleaner by lazy {
            UniffiCleaner.create()
        }
    }

    fun uniffi_siros_dc_matcher_ffi_fn_clone_sirosblobbuilder(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_siros_dc_matcher_ffi_fn_free_sirosblobbuilder(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_siros_dc_matcher_ffi_fn_constructor_sirosblobbuilder_new(uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun uniffi_siros_dc_matcher_ffi_fn_method_sirosblobbuilder_add_credential(`ptr`: Pointer,`credential`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_siros_dc_matcher_ffi_fn_method_sirosblobbuilder_add_icon(`ptr`: Pointer,`id`: RustBuffer.ByValue,`bytes`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_siros_dc_matcher_ffi_fn_method_sirosblobbuilder_add_zk_system(`ptr`: Pointer,`capability`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_siros_dc_matcher_ffi_fn_method_sirosblobbuilder_build(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_siros_dc_matcher_ffi_fn_method_sirosblobbuilder_set_debug(`ptr`: Pointer,`debug`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_siros_dc_matcher_ffi_fn_func_match_dc_api_request(`blob`: RustBuffer.ByValue,`requestJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_siros_dc_matcher_ffi_fn_func_match_dcql(`blob`: RustBuffer.ByValue,`dcqlJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_siros_dc_matcher_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_siros_dc_matcher_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_siros_dc_matcher_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_siros_dc_matcher_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_siros_dc_matcher_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_siros_dc_matcher_ffi_checksum_func_match_dc_api_request(
    ): Short
    fun uniffi_siros_dc_matcher_ffi_checksum_func_match_dcql(
    ): Short
    fun uniffi_siros_dc_matcher_ffi_checksum_method_sirosblobbuilder_add_credential(
    ): Short
    fun uniffi_siros_dc_matcher_ffi_checksum_method_sirosblobbuilder_add_icon(
    ): Short
    fun uniffi_siros_dc_matcher_ffi_checksum_method_sirosblobbuilder_add_zk_system(
    ): Short
    fun uniffi_siros_dc_matcher_ffi_checksum_method_sirosblobbuilder_build(
    ): Short
    fun uniffi_siros_dc_matcher_ffi_checksum_method_sirosblobbuilder_set_debug(
    ): Short
    fun uniffi_siros_dc_matcher_ffi_checksum_constructor_sirosblobbuilder_new(
    ): Short
    fun ffi_siros_dc_matcher_ffi_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_siros_dc_matcher_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_siros_dc_matcher_ffi_checksum_func_match_dc_api_request() != 60054.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_siros_dc_matcher_ffi_checksum_func_match_dcql() != 59469.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_siros_dc_matcher_ffi_checksum_method_sirosblobbuilder_add_credential() != 64015.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_siros_dc_matcher_ffi_checksum_method_sirosblobbuilder_add_icon() != 53556.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_siros_dc_matcher_ffi_checksum_method_sirosblobbuilder_add_zk_system() != 50234.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_siros_dc_matcher_ffi_checksum_method_sirosblobbuilder_build() != 51313.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_siros_dc_matcher_ffi_checksum_method_sirosblobbuilder_set_debug() != 60199.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_siros_dc_matcher_ffi_checksum_constructor_sirosblobbuilder_new() != 39445.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}


// This template implements a class for working with a Rust struct via a Pointer/Arc<T>
// to the live Rust struct on the other side of the FFI.
//
// Each instance implements core operations for working with the Rust `Arc<T>` and the
// Kotlin Pointer to work with the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.


private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
        AndroidSystemCleaner()
    } else {
        UniffiJnaCleaner()
    }

// The SystemCleaner, available from API Level 33.
// Some API Level 33 OSes do not support using it, so we require API Level 34.
@RequiresApi(Build.VERSION_CODES.UPSIDE_DOWN_CAKE)
private class AndroidSystemCleaner : UniffiCleaner {
    val cleaner = android.system.SystemCleaner.cleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        AndroidSystemCleanable(cleaner.register(value, cleanUpTask))
}

@RequiresApi(Build.VERSION_CODES.UPSIDE_DOWN_CAKE)
private class AndroidSystemCleanable(
    private val cleanable: java.lang.ref.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}
/**
 * Builds the blob a wallet registers with the platform.
 *
 * The profile — protocols, format mappings, `meta` handling — is supplied by
 * this builder rather than by the caller. Wallets differ in what they *hold*
 * and what they *can do*, not usually in how DCQL should be interpreted, and
 * keeping the interpretation in one place is what stops two SDKs drifting
 * apart on it.
 */
public interface SirosBlobBuilderInterface {
    
    /**
     * Add a credential.
     */
    fun `addCredential`(`credential`: FfiCredential)
    
    /**
     * Add an icon, referenced by [`FfiCredential::icon_id`].
     *
     * Stored once and shared: wallets routinely hold several credentials from
     * one issuer, and repeating that issuer's logo per credential makes the
     * registered payload grow with credentials rather than with issuers.
     */
    fun `addIcon`(`id`: kotlin.String, `bytes`: kotlin.ByteArray)
    
    /**
     * Declare a ZK proof system this wallet can actually produce.
     *
     * Without this, a `mso_mdoc_zk` request matches nothing — which is the
     * correct outcome for a wallet that cannot produce the proof.
     */
    fun `addZkSystem`(`capability`: FfiCapability)
    
    /**
     * Encode the blob to register.
     *
     * # Errors
     *
     * [`BlobError::UnknownIcon`] when a credential names an icon that was
     * never added — a dangling reference would otherwise cost that credential
     * its picture with nothing said. [`BlobError::Encoding`] if serialisation
     * fails.
     */
    fun `build`(): kotlin.ByteArray
    
    /**
     * Put matcher diagnostics into entry metadata.
     *
     * Development only. It writes matcher internals somewhere the platform
     * stores them.
     */
    fun `setDebug`(`debug`: kotlin.Boolean)
    
    companion object
}

/**
 * Builds the blob a wallet registers with the platform.
 *
 * The profile — protocols, format mappings, `meta` handling — is supplied by
 * this builder rather than by the caller. Wallets differ in what they *hold*
 * and what they *can do*, not usually in how DCQL should be interpreted, and
 * keeping the interpretation in one place is what stops two SDKs drifting
 * apart on it.
 */
open class SirosBlobBuilder: Disposable, AutoCloseable, SirosBlobBuilderInterface {

    constructor(pointer: Pointer) {
        this.pointer = pointer
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }

    /**
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noPointer: NoPointer) {
        this.pointer = null
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }
    /**
     * A builder carrying the default SIROS matching profile.
     */
    constructor() :
        this(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_siros_dc_matcher_ffi_fn_constructor_sirosblobbuilder_new(
        _status)
}
    )

    protected val pointer: Pointer?
    protected val cleanable: UniffiCleaner.Cleanable

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.uniffiClonePointer())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_siros_dc_matcher_ffi_fn_free_sirosblobbuilder(ptr, status)
                }
            }
        }
    }

    fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_siros_dc_matcher_ffi_fn_clone_sirosblobbuilder(pointer!!, status)
        }
    }

    
    /**
     * Add a credential.
     */override fun `addCredential`(`credential`: FfiCredential)
        = 
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_siros_dc_matcher_ffi_fn_method_sirosblobbuilder_add_credential(
        it, FfiConverterTypeFfiCredential.lower(`credential`),_status)
}
    }
    
    

    
    /**
     * Add an icon, referenced by [`FfiCredential::icon_id`].
     *
     * Stored once and shared: wallets routinely hold several credentials from
     * one issuer, and repeating that issuer's logo per credential makes the
     * registered payload grow with credentials rather than with issuers.
     */override fun `addIcon`(`id`: kotlin.String, `bytes`: kotlin.ByteArray)
        = 
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_siros_dc_matcher_ffi_fn_method_sirosblobbuilder_add_icon(
        it, FfiConverterString.lower(`id`),FfiConverterByteArray.lower(`bytes`),_status)
}
    }
    
    

    
    /**
     * Declare a ZK proof system this wallet can actually produce.
     *
     * Without this, a `mso_mdoc_zk` request matches nothing — which is the
     * correct outcome for a wallet that cannot produce the proof.
     */override fun `addZkSystem`(`capability`: FfiCapability)
        = 
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_siros_dc_matcher_ffi_fn_method_sirosblobbuilder_add_zk_system(
        it, FfiConverterTypeFfiCapability.lower(`capability`),_status)
}
    }
    
    

    
    /**
     * Encode the blob to register.
     *
     * # Errors
     *
     * [`BlobError::UnknownIcon`] when a credential names an icon that was
     * never added — a dangling reference would otherwise cost that credential
     * its picture with nothing said. [`BlobError::Encoding`] if serialisation
     * fails.
     */
    @Throws(BlobException::class)override fun `build`(): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    callWithPointer {
    uniffiRustCallWithError(BlobException) { _status ->
    UniffiLib.INSTANCE.uniffi_siros_dc_matcher_ffi_fn_method_sirosblobbuilder_build(
        it, _status)
}
    }
    )
    }
    

    
    /**
     * Put matcher diagnostics into entry metadata.
     *
     * Development only. It writes matcher internals somewhere the platform
     * stores them.
     */override fun `setDebug`(`debug`: kotlin.Boolean)
        = 
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_siros_dc_matcher_ffi_fn_method_sirosblobbuilder_set_debug(
        it, FfiConverterBoolean.lower(`debug`),_status)
}
    }
    
    

    

    
    
    companion object
    
}

/**
 * @suppress
 */
public object FfiConverterTypeSirosBlobBuilder: FfiConverter<SirosBlobBuilder, Pointer> {

    override fun lower(value: SirosBlobBuilder): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): SirosBlobBuilder {
        return SirosBlobBuilder(value)
    }

    override fun read(buf: ByteBuffer): SirosBlobBuilder {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: SirosBlobBuilder) = 8UL

    override fun write(value: SirosBlobBuilder, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}



/**
 * Something this wallet can produce beyond what it stores, such as a ZK proof
 * over an mdoc.
 */
data class FfiCapability (
    /**
     * System identifier, e.g. `longfellow-libzk-v1`.
     */
    var `system`: kotlin.String, 
    /**
     * Parameters that must also agree for the capability to apply.
     *
     * Supply the real ones. A ZK circuit is built for a fixed attribute
     * count, so a request naming the right system with the wrong
     * `num_attributes` is one this wallet cannot satisfy — and omitting the
     * parameter turns that into a failure after the user has consented,
     * rather than an entry that was never offered.
     */
    var `params`: Map<kotlin.String, kotlin.String>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCapability: FfiConverterRustBuffer<FfiCapability> {
    override fun read(buf: ByteBuffer): FfiCapability {
        return FfiCapability(
            FfiConverterString.read(buf),
            FfiConverterMapStringString.read(buf),
        )
    }

    override fun allocationSize(value: FfiCapability) = (
            FfiConverterString.allocationSize(value.`system`) +
            FfiConverterMapStringString.allocationSize(value.`params`)
    )

    override fun write(value: FfiCapability, buf: ByteBuffer) {
            FfiConverterString.write(value.`system`, buf)
            FfiConverterMapStringString.write(value.`params`, buf)
    }
}



/**
 * One claim, as the wallet knows it.
 */
data class FfiClaim (
    /**
     * DCQL path. For ISO mdoc this is `[namespace, element_identifier]`.
     *
     * A list, not a dotted string: ISO mdoc namespaces contain dots
     * themselves (`org.iso.18013.5.1`), so flattening and re-splitting
     * silently mis-parses every one of them.
     */
    var `path`: List<kotlin.String>, 
    /**
     * The value, used for DCQL `values` filtering.
     */
    var `value`: kotlin.String, 
    /**
     * Human-readable label.
     */
    var `display`: kotlin.String, 
    /**
     * Human-readable value, when it differs from [`Self::value`].
     */
    var `displayValue`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiClaim: FfiConverterRustBuffer<FfiClaim> {
    override fun read(buf: ByteBuffer): FfiClaim {
        return FfiClaim(
            FfiConverterSequenceString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiClaim) = (
            FfiConverterSequenceString.allocationSize(value.`path`) +
            FfiConverterString.allocationSize(value.`value`) +
            FfiConverterString.allocationSize(value.`display`) +
            FfiConverterOptionalString.allocationSize(value.`displayValue`)
    )

    override fun write(value: FfiClaim, buf: ByteBuffer) {
            FfiConverterSequenceString.write(value.`path`, buf)
            FfiConverterString.write(value.`value`, buf)
            FfiConverterString.write(value.`display`, buf)
            FfiConverterOptionalString.write(value.`displayValue`, buf)
    }
}



/**
 * One way to satisfy the request: every member presented together.
 */
data class FfiCombination (
    /**
     * The credentials making up this option.
     */
    var `members`: List<FfiMatchedCredential>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCombination: FfiConverterRustBuffer<FfiCombination> {
    override fun read(buf: ByteBuffer): FfiCombination {
        return FfiCombination(
            FfiConverterSequenceTypeFfiMatchedCredential.read(buf),
        )
    }

    override fun allocationSize(value: FfiCombination) = (
            FfiConverterSequenceTypeFfiMatchedCredential.allocationSize(value.`members`)
    )

    override fun write(value: FfiCombination, buf: ByteBuffer) {
            FfiConverterSequenceTypeFfiMatchedCredential.write(value.`members`, buf)
    }
}



/**
 * One credential the wallet holds.
 */
data class FfiCredential (
    /**
     * Wallet-side identifier, returned when the user selects this entry.
     */
    var `id`: kotlin.String, 
    /**
     * Storage format, e.g. `mso_mdoc` or `dc+sd-jwt`.
     */
    var `format`: kotlin.String, 
    /**
     * ISO mdoc docType, when this is an mdoc.
     *
     * Parse this from the credential's own MSO. Deriving it from issuer
     * metadata leaves every credential from a standards-conformant
     * third-party issuer with no docType, and therefore unmatchable, while
     * looking perfectly valid everywhere else.
     */
    var `doctype`: kotlin.String?, 
    /**
     * SD-JWT VC type, when this is an SD-JWT VC.
     */
    var `vct`: kotlin.String?, 
    /**
     * Primary line shown in the picker.
     */
    var `title`: kotlin.String, 
    /**
     * Secondary line, typically the issuer.
     */
    var `subtitle`: kotlin.String, 
    /**
     * Icon added via [`SirosBlobBuilder::add_icon`], by its id.
     */
    var `iconId`: kotlin.String?, 
    /**
     * Claims available for matching and display.
     */
    var `claims`: List<FfiClaim>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCredential: FfiConverterRustBuffer<FfiCredential> {
    override fun read(buf: ByteBuffer): FfiCredential {
        return FfiCredential(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterSequenceTypeFfiClaim.read(buf),
        )
    }

    override fun allocationSize(value: FfiCredential) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`format`) +
            FfiConverterOptionalString.allocationSize(value.`doctype`) +
            FfiConverterOptionalString.allocationSize(value.`vct`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterString.allocationSize(value.`subtitle`) +
            FfiConverterOptionalString.allocationSize(value.`iconId`) +
            FfiConverterSequenceTypeFfiClaim.allocationSize(value.`claims`)
    )

    override fun write(value: FfiCredential, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`format`, buf)
            FfiConverterOptionalString.write(value.`doctype`, buf)
            FfiConverterOptionalString.write(value.`vct`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterString.write(value.`subtitle`, buf)
            FfiConverterOptionalString.write(value.`iconId`, buf)
            FfiConverterSequenceTypeFfiClaim.write(value.`claims`, buf)
    }
}



/**
 * The outcome of matching.
 */
data class FfiMatchOutcome (
    /**
     * Per-query candidates, complete and uncapped.
     */
    var `matches`: List<FfiQueryMatch>, 
    /**
     * Whether the wallet can satisfy the request at all.
     *
     * False means §6.4's "MUST NOT return any Credential(s)" — nothing should
     * be offered, not even the part that matched.
     */
    var `satisfiable`: kotlin.Boolean, 
    /**
     * Ways to satisfy it. Alternatives are separate entries.
     */
    var `combinations`: List<FfiCombination>, 
    /**
     * How many further combinations existed beyond the returned ones.
     */
    var `dropped`: kotlin.UInt
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiMatchOutcome: FfiConverterRustBuffer<FfiMatchOutcome> {
    override fun read(buf: ByteBuffer): FfiMatchOutcome {
        return FfiMatchOutcome(
            FfiConverterSequenceTypeFfiQueryMatch.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterSequenceTypeFfiCombination.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: FfiMatchOutcome) = (
            FfiConverterSequenceTypeFfiQueryMatch.allocationSize(value.`matches`) +
            FfiConverterBoolean.allocationSize(value.`satisfiable`) +
            FfiConverterSequenceTypeFfiCombination.allocationSize(value.`combinations`) +
            FfiConverterUInt.allocationSize(value.`dropped`)
    )

    override fun write(value: FfiMatchOutcome, buf: ByteBuffer) {
            FfiConverterSequenceTypeFfiQueryMatch.write(value.`matches`, buf)
            FfiConverterBoolean.write(value.`satisfiable`, buf)
            FfiConverterSequenceTypeFfiCombination.write(value.`combinations`, buf)
            FfiConverterUInt.write(value.`dropped`, buf)
    }
}



/**
 * One credential answering one credential query.
 */
data class FfiMatchedCredential (
    /**
     * The DCQL credential query this answers.
     */
    var `queryId`: kotlin.String, 
    /**
     * The wallet-side credential identifier.
     */
    var `credentialId`: kotlin.String, 
    /**
     * Exactly the claims to disclose — and no others (§6.4).
     *
     * Each is a path: for ISO mdoc, `[namespace, element_identifier]`.
     */
    var `claims`: List<List<kotlin.String>>, 
    /**
     * The capability chosen to satisfy this query, if its format needed one.
     *
     * Returned rather than left to the caller because the engine has already
     * decided. Working it out again means parsing the request a second time,
     * in a second implementation, and possibly reaching a different answer.
     */
    var `capabilities`: List<FfiCapability>, 
    /**
     * `meta` entries the wallet needs at presentation time but which do not
     * affect matching — `ppid_context` above all, which both SDKs read today.
     *
     * A pseudonym context changes what is produced, not which credential can
     * produce it, so it is carried rather than matched on.
     */
    var `meta`: Map<kotlin.String, kotlin.String>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiMatchedCredential: FfiConverterRustBuffer<FfiMatchedCredential> {
    override fun read(buf: ByteBuffer): FfiMatchedCredential {
        return FfiMatchedCredential(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceSequenceString.read(buf),
            FfiConverterSequenceTypeFfiCapability.read(buf),
            FfiConverterMapStringString.read(buf),
        )
    }

    override fun allocationSize(value: FfiMatchedCredential) = (
            FfiConverterString.allocationSize(value.`queryId`) +
            FfiConverterString.allocationSize(value.`credentialId`) +
            FfiConverterSequenceSequenceString.allocationSize(value.`claims`) +
            FfiConverterSequenceTypeFfiCapability.allocationSize(value.`capabilities`) +
            FfiConverterMapStringString.allocationSize(value.`meta`)
    )

    override fun write(value: FfiMatchedCredential, buf: ByteBuffer) {
            FfiConverterString.write(value.`queryId`, buf)
            FfiConverterString.write(value.`credentialId`, buf)
            FfiConverterSequenceSequenceString.write(value.`claims`, buf)
            FfiConverterSequenceTypeFfiCapability.write(value.`capabilities`, buf)
            FfiConverterMapStringString.write(value.`meta`, buf)
    }
}



/**
 * The credentials answering one credential query.
 *
 * Complete, and independent of [`FfiMatchOutcome::combinations`]. Callers that
 * only need "which credentials qualify for this query" must read this rather
 * than unioning the combinations: the combination list is *capped*, because
 * its length is a product of the per-query candidate counts, so a union of it
 * can omit credentials that do qualify. Filtering on such a union silently
 * drops them from what a user is offered.
 */
data class FfiQueryMatch (
    /**
     * The DCQL credential query.
     */
    var `queryId`: kotlin.String, 
    /**
     * Every credential that satisfies it.
     */
    var `credentials`: List<FfiMatchedCredential>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiQueryMatch: FfiConverterRustBuffer<FfiQueryMatch> {
    override fun read(buf: ByteBuffer): FfiQueryMatch {
        return FfiQueryMatch(
            FfiConverterString.read(buf),
            FfiConverterSequenceTypeFfiMatchedCredential.read(buf),
        )
    }

    override fun allocationSize(value: FfiQueryMatch) = (
            FfiConverterString.allocationSize(value.`queryId`) +
            FfiConverterSequenceTypeFfiMatchedCredential.allocationSize(value.`credentials`)
    )

    override fun write(value: FfiQueryMatch, buf: ByteBuffer) {
            FfiConverterString.write(value.`queryId`, buf)
            FfiConverterSequenceTypeFfiMatchedCredential.write(value.`credentials`, buf)
    }
}





/**
 * Why a blob could not be built.
 */
sealed class BlobException: kotlin.Exception() {
    
    /**
     * The credential set could not be encoded.
     */
    class Encoding(
        
        /**
         * What went wrong.
         */
        val `reason`: kotlin.String
        ) : BlobException() {
        override val message
            get() = "reason=${ `reason` }"
    }
    
    /**
     * A credential referred to an icon that was never added.
     */
    class UnknownIcon(
        
        /**
         * The credential holding the dangling reference.
         */
        val `credentialId`: kotlin.String, 
        
        /**
         * The icon it asked for.
         */
        val `iconId`: kotlin.String
        ) : BlobException() {
        override val message
            get() = "credentialId=${ `credentialId` }, iconId=${ `iconId` }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<BlobException> {
        override fun lift(error_buf: RustBuffer.ByValue): BlobException = FfiConverterTypeBlobError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeBlobError : FfiConverterRustBuffer<BlobException> {
    override fun read(buf: ByteBuffer): BlobException {
        

        return when(buf.getInt()) {
            1 -> BlobException.Encoding(
                FfiConverterString.read(buf),
                )
            2 -> BlobException.UnknownIcon(
                FfiConverterString.read(buf),
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: BlobException): ULong {
        return when(value) {
            is BlobException.Encoding -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`reason`)
            )
            is BlobException.UnknownIcon -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`credentialId`)
                + FfiConverterString.allocationSize(value.`iconId`)
            )
        }
    }

    override fun write(value: BlobException, buf: ByteBuffer) {
        when(value) {
            is BlobException.Encoding -> {
                buf.putInt(1)
                FfiConverterString.write(value.`reason`, buf)
                Unit
            }
            is BlobException.UnknownIcon -> {
                buf.putInt(2)
                FfiConverterString.write(value.`credentialId`, buf)
                FfiConverterString.write(value.`iconId`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





/**
 * Why a request could not be matched.
 */
sealed class MatchException: kotlin.Exception() {
    
    /**
     * The registered blob could not be decoded.
     */
    class Blob(
        
        /**
         * What went wrong.
         */
        val `reason`: kotlin.String
        ) : MatchException() {
        override val message
            get() = "reason=${ `reason` }"
    }
    
    /**
     * The request was not valid JSON, or not shaped like a request.
     */
    class Request(
        
        /**
         * What went wrong.
         */
        val `reason`: kotlin.String
        ) : MatchException() {
        override val message
            get() = "reason=${ `reason` }"
    }
    
    /**
     * No protocol in the request is one this wallet can read.
     *
     * Distinct from "nothing matched": the wallet may hold exactly what was
     * asked for and still be unable to speak the protocol it was asked in.
     *
     * Carries what was offered, because a variant with no fields loses its
     * message crossing the boundary — UniFFI renders it as the case name
     * alone, so a host app logging the error would learn nothing about why.
     * The protocols the verifier named are the one thing that makes this
     * actionable.
     */
    class UnsupportedProtocol(
        
        /**
         * The protocols the request offered, in the order given.
         */
        val `offered`: List<kotlin.String>
        ) : MatchException() {
        override val message
            get() = "offered=${ `offered` }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<MatchException> {
        override fun lift(error_buf: RustBuffer.ByValue): MatchException = FfiConverterTypeMatchError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeMatchError : FfiConverterRustBuffer<MatchException> {
    override fun read(buf: ByteBuffer): MatchException {
        

        return when(buf.getInt()) {
            1 -> MatchException.Blob(
                FfiConverterString.read(buf),
                )
            2 -> MatchException.Request(
                FfiConverterString.read(buf),
                )
            3 -> MatchException.UnsupportedProtocol(
                FfiConverterSequenceString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: MatchException): ULong {
        return when(value) {
            is MatchException.Blob -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`reason`)
            )
            is MatchException.Request -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`reason`)
            )
            is MatchException.UnsupportedProtocol -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterSequenceString.allocationSize(value.`offered`)
            )
        }
    }

    override fun write(value: MatchException, buf: ByteBuffer) {
        when(value) {
            is MatchException.Blob -> {
                buf.putInt(1)
                FfiConverterString.write(value.`reason`, buf)
                Unit
            }
            is MatchException.Request -> {
                buf.putInt(2)
                FfiConverterString.write(value.`reason`, buf)
                Unit
            }
            is MatchException.UnsupportedProtocol -> {
                buf.putInt(3)
                FfiConverterSequenceString.write(value.`offered`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiCapability: FfiConverterRustBuffer<List<FfiCapability>> {
    override fun read(buf: ByteBuffer): List<FfiCapability> {
        val len = buf.getInt()
        return List<FfiCapability>(len) {
            FfiConverterTypeFfiCapability.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiCapability>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiCapability.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiCapability>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiCapability.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiClaim: FfiConverterRustBuffer<List<FfiClaim>> {
    override fun read(buf: ByteBuffer): List<FfiClaim> {
        val len = buf.getInt()
        return List<FfiClaim>(len) {
            FfiConverterTypeFfiClaim.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiClaim>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiClaim.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiClaim>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiClaim.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiCombination: FfiConverterRustBuffer<List<FfiCombination>> {
    override fun read(buf: ByteBuffer): List<FfiCombination> {
        val len = buf.getInt()
        return List<FfiCombination>(len) {
            FfiConverterTypeFfiCombination.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiCombination>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiCombination.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiCombination>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiCombination.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiMatchedCredential: FfiConverterRustBuffer<List<FfiMatchedCredential>> {
    override fun read(buf: ByteBuffer): List<FfiMatchedCredential> {
        val len = buf.getInt()
        return List<FfiMatchedCredential>(len) {
            FfiConverterTypeFfiMatchedCredential.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiMatchedCredential>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiMatchedCredential.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiMatchedCredential>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiMatchedCredential.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiQueryMatch: FfiConverterRustBuffer<List<FfiQueryMatch>> {
    override fun read(buf: ByteBuffer): List<FfiQueryMatch> {
        val len = buf.getInt()
        return List<FfiQueryMatch>(len) {
            FfiConverterTypeFfiQueryMatch.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiQueryMatch>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiQueryMatch.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiQueryMatch>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiQueryMatch.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceSequenceString: FfiConverterRustBuffer<List<List<kotlin.String>>> {
    override fun read(buf: ByteBuffer): List<List<kotlin.String>> {
        val len = buf.getInt()
        return List<List<kotlin.String>>(len) {
            FfiConverterSequenceString.read(buf)
        }
    }

    override fun allocationSize(value: List<List<kotlin.String>>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterSequenceString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<List<kotlin.String>>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterSequenceString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterMapStringString: FfiConverterRustBuffer<Map<kotlin.String, kotlin.String>> {
    override fun read(buf: ByteBuffer): Map<kotlin.String, kotlin.String> {
        val len = buf.getInt()
        return buildMap<kotlin.String, kotlin.String>(len) {
            repeat(len) {
                val k = FfiConverterString.read(buf)
                val v = FfiConverterString.read(buf)
                this[k] = v
            }
        }
    }

    override fun allocationSize(value: Map<kotlin.String, kotlin.String>): ULong {
        val spaceForMapSize = 4UL
        val spaceForChildren = value.map { (k, v) ->
            FfiConverterString.allocationSize(k) +
            FfiConverterString.allocationSize(v)
        }.sum()
        return spaceForMapSize + spaceForChildren
    }

    override fun write(value: Map<kotlin.String, kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        // The parens on `(k, v)` here ensure we're calling the right method,
        // which is important for compatibility with older android devices.
        // Ref https://blog.danlew.net/2017/03/16/kotlin-puzzler-whose-line-is-it-anyways/
        value.forEach { (k, v) ->
            FfiConverterString.write(k, buf)
            FfiConverterString.write(v, buf)
        }
    }
}
        /**
         * Match a full Digital Credentials API request.
         *
         * The request is the `{"requests":[{"protocol":…,"data":…}]}` envelope, which
         * is a list because one call can offer the same request under several
         * protocols.
         *
         * The first entry wins that the profile answers *and* that yields a query —
         * not simply the first the profile lists. ISO 18013-7 carries a CBOR
         * DeviceRequest rather than DCQL, so an entry naming it is skipped even
         * though the profile may name it, and a later entry the wallet can actually
         * read is used instead. Declining rather than failing is what makes the
         * verifier's protocol negotiation work.
         *
         * # Errors
         *
         * See [`MatchError`].
         */
    @Throws(MatchException::class) fun `matchDcApiRequest`(`blob`: kotlin.ByteArray, `requestJson`: kotlin.String): FfiMatchOutcome {
            return FfiConverterTypeFfiMatchOutcome.lift(
    uniffiRustCallWithError(MatchException) { _status ->
    UniffiLib.INSTANCE.uniffi_siros_dc_matcher_ffi_fn_func_match_dc_api_request(
        FfiConverterByteArray.lower(`blob`),FfiConverterString.lower(`requestJson`),_status)
}
    )
    }
    

        /**
         * Match a bare DCQL query.
         *
         * The wallet's own presentation flow receives a DCQL query directly rather
         * than a DC API envelope, so it has no protocol to select and none to fail
         * on.
         *
         * # Errors
         *
         * See [`MatchError`].
         */
    @Throws(MatchException::class) fun `matchDcql`(`blob`: kotlin.ByteArray, `dcqlJson`: kotlin.String): FfiMatchOutcome {
            return FfiConverterTypeFfiMatchOutcome.lift(
    uniffiRustCallWithError(MatchException) { _status ->
    UniffiLib.INSTANCE.uniffi_siros_dc_matcher_ffi_fn_func_match_dcql(
        FfiConverterByteArray.lower(`blob`),FfiConverterString.lower(`dcqlJson`),_status)
}
    )
    }
    


