// Copyright 2026 SIROS Foundation. BSD 2-Clause License.
package org.siros.sdk.credentials

import kotlinx.coroutines.runBlocking
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import uniffi.zk_cred_bbs.BbsSuiteId
import uniffi.zk_cred_bbs.jwpVerify

/**
 * [BbsProofSystem] against a real credential, on a real device.
 *
 * The native library ships as `.so` files inside an AAR, so none of this
 * can run on the JVM - which makes this the only place the Kotlin, the
 * bindings, the packaging and the Rust are exercised together.
 *
 * The fixture is generated by the crate (`make sdk-fixture`). It proves
 * nothing about whether the BBS is correct - the crate's own
 * `tests/vectors.rs` answers that differentially against Emil Lundberg's
 * TypeScript - only that a credential survives the trip through this
 * class.
 *
 * Its `plain` case has no key binding, which is what lets the whole
 * present-and-verify path run here with no authenticator attached. The
 * `keybind` case needs a Schnorr-over-BLS12-381 signature that no Android
 * key store can produce, so what is checked there is what this class asks
 * the authenticator FOR.
 */
class BbsProofSystemTest {

    private fun fixture(case: String): JSONObject {
        val stream = javaClass.classLoader!!.getResourceAsStream("bbs_jwp_fixture.json")
            ?: error("bbs_jwp_fixture.json missing from androidTest resources")
        return JSONObject(stream.bufferedReader().readText()).getJSONObject("cases").getJSONObject(case)
    }

    private fun String.unhex(): ByteArray =
        ByteArray(length / 2) { substring(it * 2, it * 2 + 2).toInt(16).toByte() }

    private fun JSONObject.hexList(key: String): List<ByteArray> =
        getJSONArray(key).let { a -> (0 until a.length()).map { a.getString(it).unhex() } }

    private fun stateOf(case: JSONObject) = BbsHolderState(
        issuerPublicKey = case.getString("issuer_pk").unhex(),
        secretProverBlind = case.getString("secret_prover_blind").unhex(),
        committedMessages = case.hexList("committed_messages"),
        keybindPublicKeys = case.hexList("keybind_public_keys"),
    )

    private fun systemFor(case: JSONObject, suite: BbsSuiteId): BbsProofSystem {
        val state = stateOf(case)
        return BbsProofSystem(
            holderState = { state },
            supportedVcts = setOf(case.getString("vct")),
            suiteId = suite,
        )
    }

    private fun spec(vararg params: Pair<String, String>) =
        ZkSystemSpec(id = "test", system = BbsProofSystem.SYSTEM_ID, params = params.toMap())

    /** Fails the test if it is ever called. */
    private val refusingSigner = ZkWitnessSigner { algorithm, _ ->
        fail("the authenticator was asked for a $algorithm signature, but this credential has no key binding")
        ByteArray(0)
    }

    private val transcript = "a session transcript".toByteArray()

    // -----------------------------------------------------------------------

    /**
     * The whole path, end to end: a stored credential becomes a
     * presentation that verifies and reveals exactly what was asked for.
     */
    @Test
    fun aCredentialPresentsAndVerifies() = runBlocking {
        val case = fixture("plain")
        val system = systemFor(case, BbsSuiteId.PLAIN)

        val result = system.generateProof(
            spec = spec("nonce" to "verifier-nonce", "aud" to "https://verifier.test"),
            document = CredentialDocument.Jwp(case.getString("issued_jwp")),
            sessionTranscript = transcript,
            requestedClaims = listOf("/given_name", "/address/country"),
            verifierIdentity = null,
            signer = refusingSigner,
        )

        val presented = result.proofBytes.toString(Charsets.UTF_8)
        assertEquals("a presented JWP has four parts", 4, presented.split(".").size)

        val verified = jwpVerify(BbsSuiteId.PLAIN, presented, case.getString("issuer_pk").unhex())
        assertEquals(case.getString("vct"), verified.vct)
        assertEquals(
            listOf("/address/country" to "\"SE\"", "/given_name" to "\"Alice\""),
            verified.disclosed.map { it.pointer to it.valueJson },
        )

        // BBS has a pseudonym construction but this does not implement it,
        // and saying so is the point of the enum - a system that quietly
        // returned nothing would be indistinguishable from one that failed.
        assertEquals(PseudonymOutcome.NOT_SUPPORTED_BY_SYSTEM, result.pseudonymOutcome)
        assertEquals(null, result.pseudonym)
        assertEquals("nothing is cached between presentations", null, result.nextState)
        assertEquals(case.getString("vct"), result.publicValues["vct"])
    }

    /**
     * Nothing beyond the requested claims may appear.
     *
     * The wallet holds a credential with eight claims and hands over one.
     * A disclosure that leaked the rest would still verify, so only this
     * catches it.
     */
    @Test
    fun onlyTheRequestedClaimsAreRevealed() = runBlocking {
        val case = fixture("plain")
        val result = systemFor(case, BbsSuiteId.PLAIN).generateProof(
            spec = spec("nonce" to "n", "aud" to "https://verifier.test"),
            document = CredentialDocument.Jwp(case.getString("issued_jwp")),
            sessionTranscript = transcript,
            requestedClaims = listOf("/birth_date"),
            verifierIdentity = null,
            signer = refusingSigner,
        )
        val verified = jwpVerify(
            BbsSuiteId.PLAIN,
            result.proofBytes.toString(Charsets.UTF_8),
            case.getString("issuer_pk").unhex(),
        )
        assertEquals(1, verified.disclosed.size)
        assertEquals("/birth_date", verified.disclosed[0].pointer)

        val leaked = result.proofBytes.toString(Charsets.UTF_8)
        for (secret in listOf("Alice", "Andersson", "Stockholm", "0f1e2d3c")) {
            assertTrue(
                "the presentation must not contain $secret",
                !leaked.contains(java.util.Base64.getUrlEncoder().withoutPadding().encodeToString("\"$secret\"".toByteArray())),
            )
        }
    }

    /**
     * Two presentations of one credential must differ.
     *
     * This is the unlinkability property the whole construction exists
     * for. It is also the one that fails silently: presentations built
     * from a fixed random source would all verify perfectly while making
     * every holder trackable across verifiers.
     */
    @Test
    fun presentationsAreUnlinkable() = runBlocking {
        val case = fixture("plain")
        val system = systemFor(case, BbsSuiteId.PLAIN)
        suspend fun present() =
            system.generateProof(
                spec = spec("nonce" to "the-same-nonce", "aud" to "https://verifier.test"),
                document = CredentialDocument.Jwp(case.getString("issued_jwp")),
                sessionTranscript = transcript,
                requestedClaims = listOf("/given_name"),
                verifierIdentity = null,
                signer = refusingSigner,
            ).proofBytes.toString(Charsets.UTF_8)

        val first = present()
        val second = present()
        assertNotEquals("same credential, same nonce, same claims - the proofs must still differ", first, second)
        // Both must verify, so the difference is re-randomisation and not damage.
        for (p in listOf(first, second)) {
            jwpVerify(BbsSuiteId.PLAIN, p, case.getString("issuer_pk").unhex())
        }
    }

    /**
     * A key bound credential asks the authenticator for exactly one
     * signature per bound key, with the algorithm that key actually uses.
     *
     * No Android key store can produce a Schnorr signature over
     * BLS12-381 G1, so the request itself is what is checked here. Getting
     * the algorithm wrong is the failure this guards: a wallet that signed
     * with ES256 instead would produce a presentation that fails
     * verification with nothing pointing at the key.
     */
    @Test
    fun aKeyBoundCredentialAsksTheAuthenticatorCorrectly() = runBlocking {
        val case = fixture("keybind")
        val asked = mutableListOf<Pair<Long, Int>>()
        val recordingSigner = ZkWitnessSigner { algorithm, data ->
            asked += algorithm to data.size
            throw UnsupportedOperationException("no BLS12-381 signer on this device")
        }

        try {
            systemFor(case, BbsSuiteId.SCHNORR).generateProof(
                spec = spec("nonce" to "n", "aud" to "https://verifier.test"),
                document = CredentialDocument.Jwp(case.getString("issued_jwp")),
                sessionTranscript = transcript,
                requestedClaims = listOf("/given_name"),
                verifierIdentity = null,
                signer = recordingSigner,
            )
            fail("a signer that cannot sign must not yield a presentation")
        } catch (e: UnsupportedOperationException) {
            assertEquals("no BLS12-381 signer on this device", e.message)
        }

        assertEquals("one signature per key binding key", 1, asked.size)
        assertEquals(COSE_ALG_BLS12381G1_SCHNORR, asked[0].first)
        assertEquals("the challenge is prehashed to 32 octets - PROFILE.md DELTA 3", 32, asked[0].second)
    }

    /**
     * The verifier's audience is not optional, and the two ways of
     * supplying it agree.
     */
    @Test
    fun theAudienceComesFromTheSpecOrTheVerifierIdentity() = runBlocking {
        val case = fixture("plain")
        val system = systemFor(case, BbsSuiteId.PLAIN)
        val jwp = CredentialDocument.Jwp(case.getString("issued_jwp"))

        suspend fun present(s: ZkSystemSpec, v: VerifierIdentity?) =
            system.generateProof(s, jwp, transcript, listOf("/given_name"), v, refusingSigner)

        // From the spec params.
        present(spec("nonce" to "n", "aud" to "https://verifier.test"), null)
        // From the verifier identity.
        present(spec("nonce" to "n"), VerifierIdentity(clientId = "https://verifier.test"))
        // From neither.
        try {
            present(spec("nonce" to "n"), null)
            fail("a presentation with no audience must be refused")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message!!, e.message!!.contains("audience"))
        }
        Unit
    }

    /**
     * Every way a caller can ask for something this credential cannot do
     * must fail before the authenticator is touched - a user prompt that
     * leads nowhere is worse than an error.
     */
    @Test
    fun impossibleRequestsAreRefused() = runBlocking {
        val case = fixture("plain")
        val system = systemFor(case, BbsSuiteId.PLAIN)
        val jwp = CredentialDocument.Jwp(case.getString("issued_jwp"))
        val ok = spec("nonce" to "n", "aud" to "https://verifier.test")

        try {
            system.generateProof(ok, jwp, transcript, listOf("/shoe_size"), null, refusingSigner)
            fail("a claim the credential does not have")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message!!, e.message!!.contains("/shoe_size"))
        }

        try {
            system.generateProof(ok, CredentialDocument.SdJwtVc(byteArrayOf(1, 2)), transcript, listOf("/given_name"), null, refusingSigner)
            fail("a document that is not a JWP")
        } catch (e: IllegalArgumentException) {
            assertTrue(e.message!!, e.message!!.contains("SdJwtVc"))
        }

        // Without the blinding factor from issuance the credential cannot
        // be presented at all, and saying so beats failing inside the
        // prover.
        val stateless = BbsProofSystem({ null }, setOf(case.getString("vct")), BbsSuiteId.PLAIN)
        try {
            stateless.generateProof(ok, jwp, transcript, listOf("/given_name"), null, refusingSigner)
            fail("no holder state")
        } catch (e: IllegalStateException) {
            assertTrue(e.message!!, e.message!!.contains("holder state"))
        }
        Unit
    }

    /**
     * The presentation is bound to the session transcript.
     *
     * Every other presentation path in this SDK binds it, and the JWP
     * drafts have no parameter for one, so this profile adds `sth`.
     * Without it a captured presentation could be replayed into a
     * different session that happened to reuse the nonce.
     */
    @Test
    fun theProofIsBoundToTheSessionTranscript() = runBlocking {
        val case = fixture("plain")
        val system = systemFor(case, BbsSuiteId.PLAIN)
        val jwp = CredentialDocument.Jwp(case.getString("issued_jwp"))

        suspend fun present(t: ByteArray) = system.generateProof(
            spec = spec("nonce" to "identical-nonce", "aud" to "https://verifier.test"),
            document = jwp,
            sessionTranscript = t,
            requestedClaims = listOf("/given_name"),
            verifierIdentity = null,
            signer = refusingSigner,
        ).proofBytes.toString(Charsets.UTF_8)

        val headerOf = { p: String -> p.split(".")[0] }
        val a = present("session one".toByteArray())
        val b = present("session two".toByteArray())
        assertNotEquals("the same nonce in two sessions must not produce the same header", headerOf(a), headerOf(b))

        // Swapping one session's header onto the other's proof must not verify.
        val spliced = listOf(headerOf(b)) + a.split(".").drop(1)
        try {
            jwpVerify(BbsSuiteId.PLAIN, spliced.joinToString("."), case.getString("issuer_pk").unhex())
            fail("a presentation replayed against another session must not verify")
        } catch (e: Exception) {
            // The crate reports verification failures opaquely on purpose.
            assertTrue(e.toString(), e is uniffi.zk_cred_bbs.BbsFfiException)
        }
        Unit
    }
}
